"use client";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsOfService() {
  return (
    <div className="flex flex-col min-h-screen bg-background bg-[linear-gradient(to_right,rgba(120,120,120,0.03)_1px,transparent_1px),linear-gradient(to_bottom,rgba(120,120,120,0.03)_1px,transparent_1px)] bg-[size:32px_32px] text-foreground font-sans animate-fade-in">
      <Navbar />
      
      <main className="flex-1 max-w-2xl w-full mx-auto px-6 py-20 space-y-8">
        <h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl text-foreground font-sans text-center mb-10">
          Terms of Service
        </h1>

        <div className="space-y-6 text-xs text-text-muted leading-relaxed">
          <p>
            Welcome to ResuTailor. By accessing or using our platform, you agree to comply with and be bound by the following Terms of Service.
          </p>

          <section className="space-y-2">
            <h2 className="text-sm font-bold text-foreground font-sans">1. Acceptable Use of Platform</h2>
            <p>
              ResuTailor is designed to help professionals honestly align their accomplishments with target job requirements. You agree not to use the service to generate fraudulent credentials, hallucinate employment history, or impersonate other professionals.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-sm font-bold text-foreground font-sans">2. User Ownership of Documents</h2>
            <p>
              You retain full ownership of all resumes, cover letters, and text files uploaded to or generated by the platform. ResuTailor does not claim any copyright over your generated content.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-sm font-bold text-foreground font-sans">3. Disclaimer of Guarantees</h2>
            <p>
              The platform is provided "as is" without warranties of any kind. While we optimize document structure for Applicant Tracking Systems (ATS), we do not guarantee job interview callbacks, hiring offers, or technical compliance with specific recruiter platforms.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-sm font-bold text-foreground font-sans">4. Local Fallback & Availability</h2>
            <p>
              ResuTailor implements local fallback engine models to operate offline or via LocalStorage during network interruptions. We are not liable for any cached data loss resulting from browser clearance or storage limitations.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-sm font-bold text-foreground font-sans">5. Updates to Terms</h2>
            <p>
              We reserve the right to modify these Terms of Service at any time. Changes will be posted to this page with an updated timestamp.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
